// Sentence-mode data for each verb.
// indicative[0-5]  → Je, Tu, Il/Elle/On, Nous, Vous, Ils/Elles
// subjunctive[0-5] → same order, with a trigger clause (que je/tu/il…)
// imperative[0-2]  → Tu, Nous, Vous
// gerund / infinitive / past_participle → single [fr, en] pair

const VERB_SENTENCES = {
    parler: {
        indicative: [
            ["Je ___ français avec ma famille.", "I speak French with my family."],
            ["Tu ___ très bien l'anglais.", "You speak English very well."],
            ["Elle ___ avec sa mère au téléphone.", "She speaks with her mother on the phone."],
            ["Nous ___ du projet ensemble.", "We speak about the project together."],
            ["Vous ___ trop vite pour moi.", "You speak too fast for me."],
            ["Ils ___ trois langues.", "They speak three languages."],
        ],
        subjunctive: [
            ["Il faut que je ___ plus lentement.", "I need to speak more slowly."],
            ["Je veux que tu ___ avec le directeur.", "I want you to speak with the director."],
            ["Il est important qu'elle ___ clairement.", "It's important that she speak clearly."],
            ["Je souhaite que nous ___ plus souvent.", "I wish we spoke more often."],
            ["Il faut que vous ___ avec respect.", "You need to speak with respect."],
            ["Je veux qu'ils ___ en français.", "I want them to speak in French."],
        ],
        imperative: [
            ["___ plus lentement, s'il te plaît.", "Speak more slowly, please."],
            ["___ en français aujourd'hui.", "Let's speak in French today."],
            ["___ avec le client demain matin.", "Speak with the client tomorrow morning."],
        ],
        gerund: ["Il apprend le français en ___ tous les jours.", "He learns French by speaking every day."],
        infinitive: ["Il est important de ___ correctement.", "It is important to speak correctly."],
        past_participle: ["J'ai ___ avec le médecin ce matin.", "I spoke with the doctor this morning."],
    },
    manger: {
        indicative: [
            ["Je ___ à la maison tous les soirs.", "I eat at home every evening."],
            ["Tu ___ trop vite.", "You eat too fast."],
            ["Il ___ une pomme pour le déjeuner.", "He eats an apple for lunch."],
            ["Nous ___ ensemble à midi.", "We eat together at noon."],
            ["Vous ___ dans ce restaurant ce soir ?", "Are you eating at this restaurant tonight?"],
            ["Ils ___ à la cantine chaque jour.", "They eat in the cafeteria every day."],
        ],
        subjunctive: [
            ["Il faut que je ___ plus sainement.", "I need to eat more healthily."],
            ["Je veux que tu ___ plus de légumes.", "I want you to eat more vegetables."],
            ["Il est important qu'il ___ avant de partir.", "It's important that he eat before leaving."],
            ["Je souhaite que nous ___ ensemble ce soir.", "I wish we ate together tonight."],
            ["Il est nécessaire que vous ___ quelque chose.", "It's necessary that you eat something."],
            ["Je veux qu'ils ___ bien pendant le voyage.", "I want them to eat well during the trip."],
        ],
        imperative: [
            ["___ ta soupe avant qu'elle refroidisse.", "Eat your soup before it gets cold."],
            ["___ quelque chose avant de partir.", "Let's eat something before leaving."],
            ["___ lentement et profitez du repas.", "Eat slowly and enjoy the meal."],
        ],
        gerund: ["Elle regarde la télévision en ___ son dîner.", "She watches television while eating her dinner."],
        infinitive: ["Il faut ___ pour vivre, pas vivre pour manger.", "One must eat to live, not live to eat."],
        past_participle: ["Nous avons ___ dans un excellent restaurant.", "We ate in an excellent restaurant."],
    },
    habiter: {
        indicative: [
            ["J'___ à Paris depuis dix ans.", "I have lived in Paris for ten years."],
            ["Tu ___ près de ton travail ?", "Do you live near your work?"],
            ["Elle ___ dans un appartement au centre-ville.", "She lives in an apartment in the city centre."],
            ["Nous ___ dans une grande maison à la campagne.", "We live in a big house in the countryside."],
            ["Vous ___ loin d'ici ?", "Do you live far from here?"],
            ["Ils ___ dans le même quartier.", "They live in the same neighbourhood."],
        ],
        subjunctive: [
            ["Il faudrait que j'___ plus près du travail.", "I should live closer to work."],
            ["Je veux que tu ___ dans un endroit sûr.", "I want you to live in a safe place."],
            ["Il est important qu'elle ___ près de ses enfants.", "It's important that she live near her children."],
            ["Je souhaite que nous ___ ensemble un jour.", "I wish we lived together one day."],
            ["Il faut que vous ___ dans un quartier calme.", "You need to live in a quiet neighbourhood."],
            ["Je veux qu'ils ___ confortablement.", "I want them to live comfortably."],
        ],
        imperative: [
            ["___ près de ton lieu de travail si possible.", "Live near your workplace if possible."],
            ["___ ensemble dans ce bel appartement.", "Let's live together in this beautiful apartment."],
            ["___ dans un endroit où vous vous sentez bien.", "Live somewhere you feel comfortable."],
        ],
        gerund: ["En ___ à l'étranger, elle a appris beaucoup.", "By living abroad, she learned a lot."],
        infinitive: ["Je rêve de ___ au bord de la mer.", "I dream of living by the sea."],
        past_participle: ["Il a ___ en France pendant cinq ans.", "He lived in France for five years."],
    },
    être: {
        indicative: [
            ["Je ___ très fatigué aujourd'hui.", "I am very tired today."],
            ["Tu ___ toujours à l'heure.", "You are always on time."],
            ["Il ___ professeur dans un lycée.", "He is a teacher in a high school."],
            ["Nous ___ prêts à commencer.", "We are ready to start."],
            ["Vous ___ en retard ce matin.", "You are late this morning."],
            ["Ils ___ contents de te voir.", "They are happy to see you."],
        ],
        subjunctive: [
            ["Il faut que je ___ plus patient.", "I need to be more patient."],
            ["Je veux que tu ___ heureux.", "I want you to be happy."],
            ["Il est important qu'elle ___ à l'heure.", "It's important that she be on time."],
            ["Je souhaite que nous ___ toujours amis.", "I wish we are always friends."],
            ["Il faut que vous ___ prêts demain.", "You need to be ready tomorrow."],
            ["Je veux qu'ils ___ en bonne santé.", "I want them to be in good health."],
        ],
        imperative: [
            ["___ courageux et ne t'inquiète pas.", "Be brave and don't worry."],
            ["___ patients et tout ira bien.", "Let's be patient and everything will be fine."],
            ["___ à l'heure pour la réunion.", "Be on time for the meeting."],
        ],
        gerund: ["En ___ attentif, tu apprendras davantage.", "By being attentive, you will learn more."],
        infinitive: ["Il est difficile de ___ parfait.", "It is difficult to be perfect."],
        past_participle: ["Elle a ___ très courageuse face à la maladie.", "She was very brave in the face of illness."],
    },
    aller: {
        indicative: [
            ["Je ___ au marché ce matin.", "I am going to the market this morning."],
            ["Tu ___ à l'école à pied ?", "Do you go to school on foot?"],
            ["Il ___ chez le médecin demain.", "He is going to the doctor tomorrow."],
            ["Nous ___ au cinéma ce soir.", "We are going to the cinema tonight."],
            ["Vous ___ en vacances en août ?", "Are you going on holiday in August?"],
            ["Ils ___ à Paris pour le week-end.", "They are going to Paris for the weekend."],
        ],
        subjunctive: [
            ["Il faut que j'___ chez le dentiste.", "I need to go to the dentist."],
            ["Je veux que tu ___ te reposer.", "I want you to go and rest."],
            ["Il est important qu'elle ___ à cette réunion.", "It's important that she go to this meeting."],
            ["Je souhaite que nous ___ ensemble.", "I wish we went together."],
            ["Il faut que vous ___ voir ce film.", "You should go and see this film."],
            ["Je veux qu'ils ___ à l'université.", "I want them to go to university."],
        ],
        imperative: [
            ["___ voir le médecin si tu ne te sens pas bien.", "Go see the doctor if you don't feel well."],
            ["___ nous promener dans le parc.", "Let's go for a walk in the park."],
            ["___ directement au bureau ce matin.", "Go straight to the office this morning."],
        ],
        gerund: ["En ___ au travail, j'écoute de la musique.", "While going to work, I listen to music."],
        infinitive: ["Je voudrais ___ en France cet été.", "I would like to go to France this summer."],
        past_participle: ["Elle est ___ à Londres la semaine dernière.", "She went to London last week."],
    },
    faire: {
        indicative: [
            ["Je ___ du sport chaque matin.", "I do sport every morning."],
            ["Tu ___ toujours tes devoirs ?", "Do you always do your homework?"],
            ["Il ___ la cuisine pour toute la famille.", "He cooks for the whole family."],
            ["Nous ___ une promenade après le dîner.", "We take a walk after dinner."],
            ["Vous ___ du bénévolat le week-end ?", "Do you volunteer at the weekend?"],
            ["Ils ___ beaucoup de progrès.", "They are making a lot of progress."],
        ],
        subjunctive: [
            ["Il faut que je ___ plus d'exercice.", "I need to do more exercise."],
            ["Je veux que tu ___ attention.", "I want you to pay attention."],
            ["Il est important qu'elle ___ ses devoirs.", "It's important that she do her homework."],
            ["Je souhaite que nous ___ un voyage ensemble.", "I wish we took a trip together."],
            ["Il faut que vous ___ un effort.", "You need to make an effort."],
            ["Je veux qu'ils ___ de leur mieux.", "I want them to do their best."],
        ],
        imperative: [
            ["___ attention à la marche.", "Watch the step."],
            ["___ de notre mieux pour réussir.", "Let's do our best to succeed."],
            ["___ vos exercices pour demain.", "Do your exercises for tomorrow."],
        ],
        gerund: ["Il écoute de la musique en ___ la vaisselle.", "He listens to music while doing the dishes."],
        infinitive: ["Il est nécessaire de ___ des efforts.", "It is necessary to make efforts."],
        past_participle: ["Qu'est-ce que tu as ___ pendant les vacances ?", "What did you do during the holidays?"],
    },
    avoir: {
        indicative: [
            ["J'___ faim après le sport.", "I am hungry after sport."],
            ["Tu ___ de la chance de vivre ici.", "You are lucky to live here."],
            ["Elle ___ une grande maison en banlieue.", "She has a large house in the suburbs."],
            ["Nous ___ un chien et un chat.", "We have a dog and a cat."],
            ["Vous ___ des questions à poser ?", "Do you have any questions to ask?"],
            ["Ils ___ beaucoup de travail cette semaine.", "They have a lot of work this week."],
        ],
        subjunctive: [
            ["Il faut que j'___ plus de patience.", "I need to have more patience."],
            ["Je veux que tu ___ confiance en toi.", "I want you to have confidence in yourself."],
            ["Il est important qu'elle ___ de bonnes notes.", "It's important that she have good grades."],
            ["Je souhaite que nous ___ plus de temps libre.", "I wish we had more free time."],
            ["Il faut que vous ___ vos documents.", "You need to have your documents."],
            ["Je veux qu'ils ___ une bonne éducation.", "I want them to have a good education."],
        ],
        imperative: [
            ["___ confiance en tes capacités.", "Have confidence in your abilities."],
            ["___ de la patience avec les enfants.", "Let's be patient with the children."],
            ["___ vos passeports prêts à la frontière.", "Have your passports ready at the border."],
        ],
        gerund: ["En ___ de bonnes habitudes, on reste en bonne santé.", "By having good habits, one stays healthy."],
        infinitive: ["Il est agréable d'___ du temps pour soi.", "It is pleasant to have time for oneself."],
        past_participle: ["Ils ont ___ beaucoup de succès.", "They had a lot of success."],
    },
    dire: {
        indicative: [
            ["Je ___ toujours la vérité.", "I always tell the truth."],
            ["Tu ___ n'importe quoi !", "You're talking nonsense!"],
            ["Elle ___ qu'elle est fatiguée.", "She says she is tired."],
            ["Nous ___ merci à nos professeurs.", "We say thank you to our teachers."],
            ["Vous ___ souvent 'oui' quand vous pensez 'non'.", "You often say yes when you mean no."],
            ["Ils ___ qu'il va pleuvoir demain.", "They say it will rain tomorrow."],
        ],
        subjunctive: [
            ["Il faut que je ___ la vérité.", "I must tell the truth."],
            ["Je veux que tu ___ ce que tu penses.", "I want you to say what you think."],
            ["Il est important qu'elle ___ son avis.", "It's important that she share her opinion."],
            ["Je souhaite que nous ___ au revoir correctement.", "I wish we said goodbye properly."],
            ["Il faut que vous ___ la vérité.", "You must tell the truth."],
            ["Je veux qu'ils ___ ce qu'ils ressentent.", "I want them to say what they feel."],
        ],
        imperative: [
            ["___ ce que tu penses sans hésiter.", "Say what you think without hesitating."],
            ["___ la vérité dans cette situation.", "Let's tell the truth in this situation."],
            ["___ à vos élèves que l'effort paie.", "Tell your students that effort pays off."],
        ],
        gerund: ["En ___ la vérité, on évite beaucoup de problèmes.", "By telling the truth, we avoid many problems."],
        infinitive: ["Il est difficile de ___ non parfois.", "It is difficult to say no sometimes."],
        past_participle: ["Il a ___ qu'il serait là à neuf heures.", "He said he would be there at nine o'clock."],
    },
    pouvoir: {
        indicative: [
            ["Je ___ vous aider si vous voulez.", "I can help you if you want."],
            ["Tu ___ venir ce soir ?", "Can you come tonight?"],
            ["Il ___ courir très vite.", "He can run very fast."],
            ["Nous ___ réserver une table pour ce soir.", "We can book a table for tonight."],
            ["Vous ___ nous appeler à tout moment.", "You can call us at any time."],
            ["Ils ___ résoudre ce problème facilement.", "They can solve this problem easily."],
        ],
        subjunctive: [
            ["Il faut que je ___ partir à l'heure.", "I need to be able to leave on time."],
            ["Je veux que tu ___ réussir.", "I want you to be able to succeed."],
            ["Il est important qu'elle ___ se défendre.", "It's important that she be able to defend herself."],
            ["Je souhaite que nous ___ travailler ensemble.", "I wish we could work together."],
            ["Il faut que vous ___ venir demain.", "You need to be able to come tomorrow."],
            ["Je veux qu'ils ___ s'en sortir.", "I want them to be able to manage."],
        ],
        imperative: [
            ["___ compter sur moi en tout temps.", "You can count on me at all times."],
            ["___ aller plus loin ensemble.", "Let's be able to go further together."],
            ["___ me contacter si vous avez besoin d'aide.", "Feel free to contact me if you need help."],
        ],
        gerund: ["En ___ compter sur ses amis, on se sent moins seul.", "By being able to count on friends, one feels less alone."],
        infinitive: ["Je voudrais ___ voyager plus souvent.", "I would like to be able to travel more often."],
        past_participle: ["Nous avons ___ résoudre le problème.", "We were able to solve the problem."],
    },
    vouloir: {
        indicative: [
            ["Je ___ apprendre le français.", "I want to learn French."],
            ["Tu ___ un café ?", "Do you want a coffee?"],
            ["Elle ___ devenir médecin.", "She wants to become a doctor."],
            ["Nous ___ changer les choses.", "We want to change things."],
            ["Vous ___ réserver votre place maintenant ?", "Do you want to reserve your seat now?"],
            ["Ils ___ partir en voyage cet été.", "They want to go on a trip this summer."],
        ],
        subjunctive: [
            ["Il faut que je ___ vraiment réussir.", "I must truly want to succeed."],
            ["Je souhaite que tu ___ bien de moi.", "I hope you think well of me."],
            ["Il est important qu'elle ___ faire des efforts.", "It's important that she want to make efforts."],
            ["Je souhaite que nous ___ la même chose.", "I wish we wanted the same thing."],
            ["Il faut que vous ___ vraiment changer.", "You must truly want to change."],
            ["Je veux qu'ils ___ continuer.", "I want them to want to continue."],
        ],
        imperative: [
            ["___ bien de moi et je te le rendrai.", "Think well of me and I'll return the favour."],
            ["___ tous réussir ensemble.", "Let's all want to succeed together."],
            ["___ bien faire et vous serez récompensés.", "Be willing to do well and you will be rewarded."],
        ],
        gerund: ["En ___ vraiment, on peut accomplir beaucoup.", "By truly wanting to, one can accomplish a great deal."],
        infinitive: ["Il est normal de ___ réussir dans la vie.", "It is normal to want to succeed in life."],
        past_participle: ["Elle n'a pas ___ venir à la fête.", "She didn't want to come to the party."],
    },
    savoir: {
        indicative: [
            ["Je ___ parler trois langues.", "I know how to speak three languages."],
            ["Tu ___ où se trouve la gare ?", "Do you know where the station is?"],
            ["Il ___ jouer du piano depuis l'âge de cinq ans.", "He has known how to play the piano since the age of five."],
            ["Nous ___ que c'est difficile.", "We know that it's difficult."],
            ["Vous ___ cuisiner ?", "Do you know how to cook?"],
            ["Ils ___ toujours quoi faire.", "They always know what to do."],
        ],
        subjunctive: [
            ["Il faut que je ___ la réponse avant demain.", "I need to know the answer before tomorrow."],
            ["Je veux que tu ___ la vérité.", "I want you to know the truth."],
            ["Il est important qu'elle ___ nager.", "It's important that she know how to swim."],
            ["Je souhaite que nous ___ travailler ensemble.", "I wish we knew how to work together."],
            ["Il faut que vous ___ vous comporter.", "You need to know how to behave."],
            ["Je veux qu'ils ___ la vérité.", "I want them to know the truth."],
        ],
        imperative: [
            ["___ que tu as toujours mon soutien.", "Know that you always have my support."],
            ["___ reconnaître nos erreurs.", "Let's know how to recognize our mistakes."],
            ["___ être à l'écoute de vos clients.", "Know how to listen to your clients."],
        ],
        gerund: ["En ___ écouter, on apprend beaucoup.", "By knowing how to listen, one learns a great deal."],
        infinitive: ["Il est utile de ___ parler plusieurs langues.", "It is useful to know how to speak several languages."],
        past_participle: ["Je n'ai jamais ___ refuser une bonne invitation.", "I have never known how to refuse a good invitation."],
    },
    voir: {
        indicative: [
            ["Je ___ un film ce soir.", "I am seeing a film tonight."],
            ["Tu ___ souvent ta famille ?", "Do you see your family often?"],
            ["Elle ___ très bien sans lunettes.", "She sees very well without glasses."],
            ["Nous ___ le problème clairement.", "We see the problem clearly."],
            ["Vous ___ ce que je veux dire ?", "Do you see what I mean?"],
            ["Ils ___ leurs amis tous les week-ends.", "They see their friends every weekend."],
        ],
        subjunctive: [
            ["Il faut que je ___ un médecin.", "I need to see a doctor."],
            ["Je veux que tu ___ la réalité.", "I want you to see reality."],
            ["Il est important qu'elle ___ ses erreurs.", "It's important that she see her mistakes."],
            ["Je souhaite que nous ___ les choses différemment.", "I wish we saw things differently."],
            ["Il faut que vous ___ ce film.", "You should see this film."],
            ["Je veux qu'ils ___ les conséquences.", "I want them to see the consequences."],
        ],
        imperative: [
            ["___ un médecin si tu ne te sens pas bien.", "See a doctor if you don't feel well."],
            ["___ les choses du bon côté.", "Let's see things from the positive side."],
            ["___ un conseiller avant de prendre une décision.", "See an advisor before making a decision."],
        ],
        gerund: ["En ___ le monde, on comprend mieux les autres.", "By seeing the world, one understands others better."],
        infinitive: ["J'aimerais ___ la tour Eiffel un jour.", "I would like to see the Eiffel Tower one day."],
        past_participle: ["Nous avons ___ un très beau spectacle.", "We saw a very beautiful show."],
    },
    venir: {
        indicative: [
            ["Je ___ te voir demain matin.", "I am coming to see you tomorrow morning."],
            ["Tu ___ à la fête ce soir ?", "Are you coming to the party tonight?"],
            ["Il ___ du Canada.", "He comes from Canada."],
            ["Nous ___ de finir notre projet.", "We have just finished our project."],
            ["Vous ___ souvent dans ce quartier ?", "Do you come to this neighbourhood often?"],
            ["Ils ___ nous rendre visite le week-end prochain.", "They are coming to visit us next weekend."],
        ],
        subjunctive: [
            ["Il faut que je ___ te voir.", "I need to come and see you."],
            ["Je veux que tu ___ à ma fête.", "I want you to come to my party."],
            ["Il est important qu'il ___ à la réunion.", "It's important that he come to the meeting."],
            ["Je souhaite que nous ___ tous ensemble.", "I wish we all came together."],
            ["Il faut que vous ___ à temps.", "You need to come on time."],
            ["Je veux qu'ils ___ nous aider.", "I want them to come and help us."],
        ],
        imperative: [
            ["___ me voir quand tu as le temps.", "Come and see me when you have time."],
            ["___ ensemble pour préparer la fête.", "Let's come together to prepare the party."],
            ["___ nous voir quand vous serez à Paris.", "Come and see us when you are in Paris."],
        ],
        gerund: ["En ___ de loin, ils ont montré leur dévouement.", "By coming from far away, they showed their dedication."],
        infinitive: ["Il peut ___ n'importe quand.", "He can come any time."],
        past_participle: ["Elle est ___ à pied depuis la gare.", "She came on foot from the station."],
    },
    prendre: {
        indicative: [
            ["Je ___ le bus pour aller au travail.", "I take the bus to go to work."],
            ["Tu ___ du sucre dans ton café ?", "Do you take sugar in your coffee?"],
            ["Elle ___ une douche le matin.", "She takes a shower in the morning."],
            ["Nous ___ le train de sept heures.", "We take the seven o'clock train."],
            ["Vous ___ la bonne direction.", "You are taking the right direction."],
            ["Ils ___ leurs vacances en juillet.", "They take their holidays in July."],
        ],
        subjunctive: [
            ["Il faut que je ___ ma décision rapidement.", "I need to make my decision quickly."],
            ["Je veux que tu ___ soin de toi.", "I want you to take care of yourself."],
            ["Il est important qu'elle ___ du repos.", "It's important that she take some rest."],
            ["Je souhaite que nous ___ le temps de réfléchir.", "I wish we took time to think."],
            ["Il faut que vous ___ cette opportunité.", "You need to take this opportunity."],
            ["Je veux qu'ils ___ leurs responsabilités.", "I want them to take their responsibilities."],
        ],
        imperative: [
            ["___ ton parapluie, il va pleuvoir.", "Take your umbrella, it's going to rain."],
            ["___ le temps de bien réfléchir.", "Let's take time to think carefully."],
            ["___ vos médicaments à la même heure chaque jour.", "Take your medication at the same time each day."],
        ],
        gerund: ["En ___ le métro, j'économise du temps.", "By taking the metro, I save time."],
        infinitive: ["Il vaut mieux ___ le train que la voiture.", "It is better to take the train than the car."],
        past_participle: ["J'ai ___ une bonne décision.", "I made a good decision."],
    },
    devoir: {
        indicative: [
            ["Je ___ finir ce rapport avant vendredi.", "I must finish this report before Friday."],
            ["Tu ___ travailler plus sérieusement.", "You must work more seriously."],
            ["Il ___ rentrer avant minuit.", "He must return home before midnight."],
            ["Nous ___ prendre une décision rapidement.", "We must make a decision quickly."],
            ["Vous ___ respecter les règles.", "You must respect the rules."],
            ["Ils ___ arriver dans une heure.", "They must arrive in an hour."],
        ],
        subjunctive: [
            ["Il faut que je ___ partir tôt.", "I have to leave early."],
            ["Je veux que tu ___ faire des efforts.", "I want you to have to make efforts."],
            ["Il est important qu'elle ___ rendre des comptes.", "It's important that she be accountable."],
            ["Je souhaite que nous ___ travailler moins.", "I wish we had to work less."],
            ["Il faut que vous ___ être responsables.", "You need to be responsible."],
            ["Je veux qu'ils ___ assumer leurs erreurs.", "I want them to have to own their mistakes."],
        ],
        imperative: [
            ["___ respecter tes engagements.", "You must respect your commitments."],
            ["___ être plus responsables à l'avenir.", "We must be more responsible in the future."],
            ["___ remettre vos rapports vendredi.", "You must hand in your reports on Friday."],
        ],
        gerund: ["En ___ faire plus avec moins, on devient créatif.", "By having to do more with less, one becomes creative."],
        infinitive: ["On ___ apprendre de ses erreurs.", "One must learn from one's mistakes."],
        past_participle: ["Elle a ___ annuler sa réunion.", "She had to cancel her meeting."],
    },
    écrire: {
        indicative: [
            ["J'___ une lettre à ma grand-mère.", "I am writing a letter to my grandmother."],
            ["Tu ___ très bien en français.", "You write very well in French."],
            ["Il ___ un roman depuis deux ans.", "He has been writing a novel for two years."],
            ["Nous ___ un rapport pour le directeur.", "We are writing a report for the director."],
            ["Vous ___ à la main ou à l'ordinateur ?", "Do you write by hand or on the computer?"],
            ["Ils ___ des articles pour un journal local.", "They write articles for a local newspaper."],
        ],
        subjunctive: [
            ["Il faut que j'___ à mon professeur.", "I need to write to my teacher."],
            ["Je veux que tu ___ plus clairement.", "I want you to write more clearly."],
            ["Il est important qu'elle ___ ses pensées.", "It's important that she write her thoughts."],
            ["Je souhaite que nous ___ quelque chose ensemble.", "I wish we wrote something together."],
            ["Il faut que vous ___ vos observations.", "You need to write down your observations."],
            ["Je veux qu'ils ___ leurs idées.", "I want them to write their ideas."],
        ],
        imperative: [
            ["___ à tes parents, ils s'inquiètent.", "Write to your parents, they are worried."],
            ["___ nos idées avant de les oublier.", "Let's write our ideas down before we forget them."],
            ["___ vos réponses clairement et lisiblement.", "Write your answers clearly and legibly."],
        ],
        gerund: ["En ___ régulièrement, tu améliores ton style.", "By writing regularly, you improve your style."],
        infinitive: ["Il est thérapeutique d'___ ses émotions.", "It is therapeutic to write about one's emotions."],
        past_participle: ["Elle a ___ un poème magnifique.", "She wrote a beautiful poem."],
    },
    lire: {
        indicative: [
            ["Je ___ un livre passionnant en ce moment.", "I am reading a fascinating book at the moment."],
            ["Tu ___ le journal chaque matin ?", "Do you read the newspaper every morning?"],
            ["Elle ___ des romans policiers.", "She reads detective novels."],
            ["Nous ___ les nouvelles en ligne.", "We read the news online."],
            ["Vous ___ beaucoup de livres par an ?", "Do you read many books a year?"],
            ["Ils ___ des bandes dessinées le week-end.", "They read comics at the weekend."],
        ],
        subjunctive: [
            ["Il faut que je ___ ce livre avant la réunion.", "I need to read this book before the meeting."],
            ["Je veux que tu ___ cet article.", "I want you to read this article."],
            ["Il est important qu'elle ___ les instructions.", "It's important that she read the instructions."],
            ["Je souhaite que nous ___ plus souvent.", "I wish we read more often."],
            ["Il faut que vous ___ le contrat attentivement.", "You need to read the contract carefully."],
            ["Je veux qu'ils ___ ce rapport.", "I want them to read this report."],
        ],
        imperative: [
            ["___ ce livre, il est vraiment bien.", "Read this book, it's really good."],
            ["___ plus de littérature française.", "Let's read more French literature."],
            ["___ les consignes avant de commencer.", "Read the instructions before you start."],
        ],
        gerund: ["En ___ chaque jour, tu enrichis ton vocabulaire.", "By reading every day, you enrich your vocabulary."],
        infinitive: ["Apprendre à ___ est l'une des compétences les plus importantes.", "Learning to read is one of the most important skills."],
        past_participle: ["J'ai ___ tous ses livres.", "I have read all his books."],
    },
    mettre: {
        indicative: [
            ["Je ___ mes clés toujours au même endroit.", "I always put my keys in the same place."],
            ["Tu ___ du sucre dans ton thé ?", "Do you put sugar in your tea?"],
            ["Il ___ une heure pour aller au travail.", "He takes an hour to get to work."],
            ["Nous ___ la table pour le dîner.", "We set the table for dinner."],
            ["Vous ___ trop de pression sur vous-mêmes.", "You put too much pressure on yourselves."],
            ["Ils ___ leurs affaires en ordre.", "They are putting their affairs in order."],
        ],
        subjunctive: [
            ["Il faut que je ___ de l'ordre dans mes papiers.", "I need to put my papers in order."],
            ["Je veux que tu ___ plus d'effort.", "I want you to put in more effort."],
            ["Il est important qu'elle ___ son manteau.", "It's important that she put on her coat."],
            ["Je souhaite que nous ___ fin à ce conflit.", "I wish we put an end to this conflict."],
            ["Il faut que vous ___ vos téléphones en silencieux.", "You need to put your phones on silent."],
            ["Je veux qu'ils ___ leurs compétences en valeur.", "I want them to put their skills to good use."],
        ],
        imperative: [
            ["___ tes affaires à leur place.", "Put your things in their place."],
            ["___ nos ressources en commun.", "Let's pool our resources together."],
            ["___ vos téléphones de côté pendant la réunion.", "Put your phones away during the meeting."],
        ],
        gerund: ["En ___ la table, elle pensait à la soirée.", "While setting the table, she was thinking about the evening."],
        infinitive: ["Il est important de ___ ses priorités en ordre.", "It is important to put one's priorities in order."],
        past_participle: ["Il a ___ deux heures pour faire ce travail.", "He took two hours to do this work."],
    },
    sortir: {
        indicative: [
            ["Je ___ souvent le week-end avec des amis.", "I often go out at the weekend with friends."],
            ["Tu ___ ce soir ?", "Are you going out tonight?"],
            ["Elle ___ de son bureau à dix-huit heures.", "She leaves her office at six o'clock."],
            ["Nous ___ dîner chaque vendredi.", "We go out for dinner every Friday."],
            ["Vous ___ souvent dans ce quartier ?", "Do you go out often in this neighbourhood?"],
            ["Ils ___ le chien deux fois par jour.", "They take the dog out twice a day."],
        ],
        subjunctive: [
            ["Il faut que je ___ prendre l'air.", "I need to go out for some fresh air."],
            ["Je veux que tu ___ de la maison.", "I want you to get out of the house."],
            ["Il est important qu'elle ___ du bureau à l'heure.", "It's important that she leave the office on time."],
            ["Je souhaite que nous ___ ensemble ce week-end.", "I wish we went out together this weekend."],
            ["Il faut que vous ___ davantage.", "You need to go out more."],
            ["Je veux qu'ils ___ de cette situation.", "I want them to get out of this situation."],
        ],
        imperative: [
            ["___ prendre l'air, tu as l'air fatigué.", "Go out for some fresh air, you look tired."],
            ["___ tous ensemble pour fêter ça.", "Let's all go out together to celebrate."],
            ["___ par la porte de derrière.", "Go out through the back door."],
        ],
        gerund: ["En ___ régulièrement, on maintient un bon équilibre.", "By going out regularly, one maintains a good balance."],
        infinitive: ["Il aime ___ le soir avec ses amis.", "He likes to go out in the evenings with his friends."],
        past_participle: ["Elle est ___ sans dire au revoir.", "She left without saying goodbye."],
    },
    finir: {
        indicative: [
            ["Je ___ mon travail avant de rentrer.", "I finish my work before going home."],
            ["Tu ___ toujours à quelle heure ?", "What time do you always finish?"],
            ["Il ___ son repas en quelques minutes.", "He finishes his meal in a few minutes."],
            ["Nous ___ le projet vendredi soir.", "We finish the project Friday evening."],
            ["Vous ___ tôt le vendredi ?", "Do you finish early on Fridays?"],
            ["Ils ___ leurs études cette année.", "They finish their studies this year."],
        ],
        subjunctive: [
            ["Il faut que je ___ ce rapport ce soir.", "I need to finish this report tonight."],
            ["Je veux que tu ___ tes devoirs avant de jouer.", "I want you to finish your homework before playing."],
            ["Il est important qu'elle ___ ce qu'elle a commencé.", "It's important that she finish what she started."],
            ["Je souhaite que nous ___ à temps.", "I wish we finished on time."],
            ["Il faut que vous ___ avant demain matin.", "You need to finish before tomorrow morning."],
            ["Je veux qu'ils ___ ce projet.", "I want them to finish this project."],
        ],
        imperative: [
            ["___ tes devoirs avant de regarder la télévision.", "Finish your homework before watching television."],
            ["___ ce que nous avons commencé.", "Let's finish what we started."],
            ["___ vos exercices avant la sonnerie.", "Finish your exercises before the bell."],
        ],
        gerund: ["En ___ tôt, tu auras du temps libre.", "By finishing early, you will have free time."],
        infinitive: ["Il faut ___ ce qu'on commence.", "One must finish what one starts."],
        past_participle: ["Avez-vous ___ votre rapport ?", "Have you finished your report?"],
    },
    travailler: {
        indicative: [
            ["Je ___ dans une banque depuis cinq ans.", "I have worked in a bank for five years."],
            ["Tu ___ beaucoup en ce moment.", "You are working a lot at the moment."],
            ["Elle ___ de chez elle trois jours par semaine.", "She works from home three days a week."],
            ["Nous ___ en équipe sur ce projet.", "We work as a team on this project."],
            ["Vous ___ le week-end ?", "Do you work at the weekend?"],
            ["Ils ___ dur pour finir avant la date limite.", "They are working hard to finish before the deadline."],
        ],
        subjunctive: [
            ["Il faut que je ___ plus sérieusement.", "I need to work more seriously."],
            ["Je veux que tu ___ moins ce week-end.", "I want you to work less this weekend."],
            ["Il est important qu'elle ___ en équipe.", "It's important that she work in a team."],
            ["Je souhaite que nous ___ mieux ensemble.", "I wish we worked better together."],
            ["Il faut que vous ___ sur votre communication.", "You need to work on your communication."],
            ["Je veux qu'ils ___ plus efficacement.", "I want them to work more efficiently."],
        ],
        imperative: [
            ["___ un peu plus et tu verras les résultats.", "Work a bit harder and you'll see the results."],
            ["___ ensemble pour trouver une solution.", "Let's work together to find a solution."],
            ["___ en silence pendant l'examen.", "Work in silence during the exam."],
        ],
        gerund: ["En ___ chaque jour, on progresse peu à peu.", "By working every day, one progresses little by little."],
        infinitive: ["Il est important de ___ en équipe.", "It is important to work as a team."],
        past_participle: ["Elle a ___ toute la nuit pour finir le projet.", "She worked all night to finish the project."],
    },
    choisir: {
        indicative: [
            ["Je ___ toujours le même plat dans ce restaurant.", "I always choose the same dish in this restaurant."],
            ["Tu ___ quoi faire ce week-end ?", "Are you choosing what to do this weekend?"],
            ["Elle ___ ses vêtements avec soin.", "She chooses her clothes carefully."],
            ["Nous ___ le meilleur candidat ensemble.", "We choose the best candidate together."],
            ["Vous ___ souvent selon vos habitudes ?", "Do you often choose based on your habits?"],
            ["Ils ___ toujours la qualité sur la quantité.", "They always choose quality over quantity."],
        ],
        subjunctive: [
            ["Il faut que je ___ une carrière rapidement.", "I need to choose a career quickly."],
            ["Je veux que tu ___ ce qui te rend heureux.", "I want you to choose what makes you happy."],
            ["Il est important qu'elle ___ librement.", "It's important that she choose freely."],
            ["Je souhaite que nous ___ ensemble.", "I wish we chose together."],
            ["Il faut que vous ___ avant la fin de la semaine.", "You need to choose before the end of the week."],
            ["Je veux qu'ils ___ la meilleure option.", "I want them to choose the best option."],
        ],
        imperative: [
            ["___ ce qui te convient le mieux.", "Choose what suits you best."],
            ["___ nos priorités pour l'année prochaine.", "Let's choose our priorities for next year."],
            ["___ votre destination avant de réserver.", "Choose your destination before booking."],
        ],
        gerund: ["En ___ soigneusement, on évite les regrets.", "By choosing carefully, one avoids regrets."],
        infinitive: ["Il est difficile de ___ entre ces deux options.", "It is difficult to choose between these two options."],
        past_participle: ["Nous avons ___ le meilleur hôtel.", "We chose the best hotel."],
    },
    partir: {
        indicative: [
            ["Je ___ en vacances la semaine prochaine.", "I am leaving on holiday next week."],
            ["Tu ___ à quelle heure ce matin ?", "What time are you leaving this morning?"],
            ["Elle ___ travailler à l'étranger.", "She is leaving to work abroad."],
            ["Nous ___ tôt pour éviter les embouteillages.", "We are leaving early to avoid traffic."],
            ["Vous ___ en train ou en voiture ?", "Are you leaving by train or by car?"],
            ["Ils ___ sans dire au revoir.", "They are leaving without saying goodbye."],
        ],
        subjunctive: [
            ["Il faut que je ___ maintenant.", "I need to leave now."],
            ["Je veux que tu ___ de bonne humeur.", "I want you to leave in a good mood."],
            ["Il est important qu'elle ___ à l'heure.", "It's important that she leave on time."],
            ["Je souhaite que nous ___ ensemble.", "I wish we left together."],
            ["Il faut que vous ___ avant midi.", "You need to leave before noon."],
            ["Je veux qu'ils ___ en sécurité.", "I want them to leave safely."],
        ],
        imperative: [
            ["___ maintenant ou tu seras en retard.", "Leave now or you will be late."],
            ["___ tôt pour éviter les embouteillages.", "Let's leave early to avoid traffic."],
            ["___ de bonne heure pour arriver à temps.", "Leave in good time to arrive on time."],
        ],
        gerund: ["En ___ tôt, ils ont évité les bouchons.", "By leaving early, they avoided the traffic jams."],
        infinitive: ["Il est difficile de ___ sa famille.", "It is difficult to leave one's family."],
        past_participle: ["Il est ___ sans prévenir personne.", "He left without warning anyone."],
    },
    donner: {
        indicative: [
            ["Je ___ des cours particuliers le mercredi.", "I give private lessons on Wednesdays."],
            ["Tu ___ souvent des cadeaux à tes amis ?", "Do you often give gifts to your friends?"],
            ["Elle ___ de son temps aux autres.", "She gives her time to others."],
            ["Nous ___ de l'argent à une association caritative.", "We give money to a charitable organisation."],
            ["Vous ___ le bon exemple à vos élèves.", "You give a good example to your students."],
            ["Ils ___ leur avis sur le projet.", "They give their opinion on the project."],
        ],
        subjunctive: [
            ["Il faut que je ___ une réponse avant vendredi.", "I need to give an answer before Friday."],
            ["Je veux que tu ___ une chance aux autres.", "I want you to give others a chance."],
            ["Il est important qu'elle ___ son accord.", "It's important that she give her agreement."],
            ["Je souhaite que nous ___ plus à ceux qui en ont besoin.", "I wish we gave more to those in need."],
            ["Il faut que vous ___ votre accord.", "You need to give your approval."],
            ["Je veux qu'ils ___ leur meilleur.", "I want them to give their best."],
        ],
        imperative: [
            ["___ moi ta main, je vais t'aider.", "Give me your hand, I will help you."],
            ["___ de notre temps aux autres cette année.", "Let's give our time to others this year."],
            ["___ vos réponses à la fin de l'heure.", "Give your answers at the end of the hour."],
        ],
        gerund: ["En ___ de son temps, on reçoit beaucoup en retour.", "By giving one's time, one receives a great deal in return."],
        infinitive: ["Il est généreux de ___ sans rien attendre en retour.", "It is generous to give without expecting anything in return."],
        past_participle: ["Il a ___ sa démission hier matin.", "He handed in his resignation yesterday morning."],
    },
    comprendre: {
        indicative: [
            ["Je ___ la situation maintenant.", "I understand the situation now."],
            ["Tu ___ ce que je veux dire ?", "Do you understand what I mean?"],
            ["Elle ___ le français parfaitement.", "She understands French perfectly."],
            ["Nous ___ vos préoccupations.", "We understand your concerns."],
            ["Vous ___ les enjeux de cette décision ?", "Do you understand the issues of this decision?"],
            ["Ils ___ enfin pourquoi c'est important.", "They finally understand why it's important."],
        ],
        subjunctive: [
            ["Il faut que je ___ mieux la situation.", "I need to understand the situation better."],
            ["Je veux que tu ___ mon point de vue.", "I want you to understand my point of view."],
            ["Il est important qu'elle ___ les règles.", "It's important that she understand the rules."],
            ["Je souhaite que nous ___ mieux nos différences.", "I wish we better understood our differences."],
            ["Il faut que vous ___ les enjeux.", "You need to understand the issues."],
            ["Je veux qu'ils ___ la gravité de la situation.", "I want them to understand the seriousness of the situation."],
        ],
        imperative: [
            ["___ que je t'aide par amitié.", "Understand that I'm helping you out of friendship."],
            ["___ les besoins de nos clients.", "Let's understand the needs of our clients."],
            ["___ bien les règles avant de commencer.", "Understand the rules clearly before starting."],
        ],
        gerund: ["En ___ mieux la culture, on communique mieux.", "By better understanding the culture, one communicates better."],
        infinitive: ["Il est essentiel de ___ avant de juger.", "It is essential to understand before judging."],
        past_participle: ["Je n'ai pas ___ ce qu'il a dit.", "I didn't understand what he said."],
    },
    commencer: {
        indicative: [
            ["Je ___ un nouveau livre ce soir.", "I am starting a new book tonight."],
            ["Tu ___ à travailler à quelle heure ?", "What time do you start working?"],
            ["Il ___ à comprendre le français.", "He is beginning to understand French."],
            ["Nous ___ la réunion à neuf heures.", "We start the meeting at nine o'clock."],
            ["Vous ___ votre nouveau poste lundi ?", "Are you starting your new position on Monday?"],
            ["Ils ___ à perdre patience.", "They are beginning to lose patience."],
        ],
        subjunctive: [
            ["Il faut que je ___ immédiatement.", "I need to start immediately."],
            ["Je veux que tu ___ dès maintenant.", "I want you to start right away."],
            ["Il est important qu'elle ___ à temps.", "It's important that she start on time."],
            ["Je souhaite que nous ___ une nouvelle page.", "I wish we started a new chapter."],
            ["Il faut que vous ___ ce projet.", "You need to start this project."],
            ["Je veux qu'ils ___ leur travail sans tarder.", "I want them to start their work without delay."],
        ],
        imperative: [
            ["___ par le commencement.", "Start from the beginning."],
            ["___ par définir nos objectifs.", "Let's start by defining our objectives."],
            ["___ vos travaux dans le calme.", "Start your work calmly."],
        ],
        gerund: ["En ___ tôt, on a plus de chances de réussir.", "By starting early, one has a better chance of succeeding."],
        infinitive: ["Il est difficile de ___ quand on manque de motivation.", "It is difficult to start when one lacks motivation."],
        past_participle: ["Avons-nous ___ à la bonne heure ?", "Did we start at the right time?"],
    },
    arriver: {
        indicative: [
            ["J'___ toujours à l'heure.", "I always arrive on time."],
            ["Tu ___ à quelle heure ce soir ?", "What time are you arriving tonight?"],
            ["Elle ___ de Londres demain matin.", "She is arriving from London tomorrow morning."],
            ["Nous ___ en avance pour préparer la salle.", "We arrive early to prepare the room."],
            ["Vous ___ souvent en retard ?", "Do you often arrive late?"],
            ["Ils ___ après un long voyage.", "They arrive after a long journey."],
        ],
        subjunctive: [
            ["Il faut que j'___ avant dix heures.", "I need to arrive before ten o'clock."],
            ["Je veux que tu ___ à temps.", "I want you to arrive on time."],
            ["Il est important qu'elle ___ avant la nuit.", "It's important that she arrive before nightfall."],
            ["Je souhaite que nous ___ ensemble.", "I wish we arrived together."],
            ["Il faut que vous ___ avant les autres.", "You need to arrive before the others."],
            ["Je veux qu'ils ___ sans problème.", "I want them to arrive without any problems."],
        ],
        imperative: [
            ["___ de bonne heure pour avoir une bonne place.", "Arrive early to get a good seat."],
            ["___ en avance pour mettre en place la salle.", "Let's arrive early to set up the room."],
            ["___ à temps pour la réunion.", "Arrive on time for the meeting."],
        ],
        gerund: ["En ___ tôt, elle a pu choisir la meilleure place.", "By arriving early, she was able to choose the best seat."],
        infinitive: ["Il est toujours préférable d'___ à l'heure.", "It is always preferable to arrive on time."],
        past_participle: ["Ils sont ___ sans prévenir.", "They arrived without warning."],
    },
    chercher: {
        indicative: [
            ["Je ___ mes clés depuis ce matin.", "I have been looking for my keys since this morning."],
            ["Tu ___ quelque chose ?", "Are you looking for something?"],
            ["Il ___ un appartement à louer.", "He is looking for a flat to rent."],
            ["Nous ___ une solution à ce problème.", "We are looking for a solution to this problem."],
            ["Vous ___ un emploi en ce moment ?", "Are you looking for a job at the moment?"],
            ["Ils ___ leurs enfants à l'école.", "They pick up their children from school."],
        ],
        subjunctive: [
            ["Il faut que je ___ une autre solution.", "I need to look for another solution."],
            ["Je veux que tu ___ un appartement plus grand.", "I want you to look for a bigger flat."],
            ["Il est important qu'elle ___ de l'aide.", "It's important that she look for help."],
            ["Je souhaite que nous ___ ensemble.", "I wish we looked for a solution together."],
            ["Il faut que vous ___ les documents.", "You need to look for the documents."],
            ["Je veux qu'ils ___ des alternatives.", "I want them to look for alternatives."],
        ],
        imperative: [
            ["___ tes affaires avant de partir.", "Look for your things before leaving."],
            ["___ une solution créative à ce défi.", "Let's look for a creative solution to this challenge."],
            ["___ les informations dans le manuel.", "Look for the information in the manual."],
        ],
        gerund: ["En ___ bien, tu finiras par trouver.", "By looking carefully, you will eventually find it."],
        infinitive: ["Il faut ___ pour trouver.", "One must search in order to find."],
        past_participle: ["Elle a ___ ses lunettes partout.", "She looked for her glasses everywhere."],
    },
    acheter: {
        indicative: [
            ["J'___ mes légumes au marché local.", "I buy my vegetables at the local market."],
            ["Tu ___ souvent en ligne ?", "Do you often buy online?"],
            ["Elle ___ un cadeau pour son ami.", "She is buying a gift for her friend."],
            ["Nous ___ une nouvelle voiture ce mois-ci.", "We are buying a new car this month."],
            ["Vous ___ souvent des livres ?", "Do you often buy books?"],
            ["Ils ___ leur maison en banlieue.", "They are buying their house in the suburbs."],
        ],
        subjunctive: [
            ["Il faut que j'___ du pain ce soir.", "I need to buy some bread tonight."],
            ["Je veux que tu ___ ce livre.", "I want you to buy this book."],
            ["Il est important qu'elle ___ des médicaments.", "It's important that she buy some medicine."],
            ["Je souhaite que nous ___ une maison ensemble.", "I wish we bought a house together."],
            ["Il faut que vous ___ vos billets à l'avance.", "You need to buy your tickets in advance."],
            ["Je veux qu'ils ___ de bons produits.", "I want them to buy good quality products."],
        ],
        imperative: [
            ["___ du lait en rentrant.", "Buy some milk on the way home."],
            ["___ des cadeaux pour tout le monde.", "Let's buy gifts for everyone."],
            ["___ vos billets d'avion dès que possible.", "Buy your plane tickets as soon as possible."],
        ],
        gerund: ["En ___ en vrac, on fait des économies.", "By buying in bulk, one saves money."],
        infinitive: ["Il faut ___ local pour soutenir les producteurs.", "One should buy local to support producers."],
        past_participle: ["Elle a ___ une robe magnifique.", "She bought a beautiful dress."],
    },
    croire: {
        indicative: [
            ["Je ___ en l'avenir de ce projet.", "I believe in the future of this project."],
            ["Tu ___ ce qu'il dit ?", "Do you believe what he says?"],
            ["Elle ___ aux miracles.", "She believes in miracles."],
            ["Nous ___ qu'il est possible de réussir.", "We believe it is possible to succeed."],
            ["Vous ___ vraiment en cette solution ?", "Do you really believe in this solution?"],
            ["Ils ___ que la situation va s'améliorer.", "They believe the situation will improve."],
        ],
        subjunctive: [
            ["Il faut que je ___ davantage en moi.", "I need to believe in myself more."],
            ["Je veux que tu ___ en tes capacités.", "I want you to believe in your abilities."],
            ["Il est important qu'elle ___ en ce projet.", "It's important that she believe in this project."],
            ["Je souhaite que nous ___ en l'avenir.", "I wish we believed in the future."],
            ["Il faut que vous ___ en votre équipe.", "You need to believe in your team."],
            ["Je veux qu'ils ___ en eux-mêmes.", "I want them to believe in themselves."],
        ],
        imperative: [
            ["___ en toi et tu réussiras.", "Believe in yourself and you will succeed."],
            ["___ en notre capacité à changer les choses.", "Let's believe in our ability to change things."],
            ["___ ce que vos yeux vous montrent.", "Believe what your eyes show you."],
        ],
        gerund: ["En ___ en soi, on surmonte tous les obstacles.", "By believing in oneself, one overcomes all obstacles."],
        infinitive: ["Il est facile de ___ ce qu'on veut entendre.", "It is easy to believe what one wants to hear."],
        past_participle: ["Il a ___ tout ce qu'on lui a dit.", "He believed everything he was told."],
    },
    connaître: {
        indicative: [
            ["Je ___ bien ce quartier.", "I know this neighbourhood well."],
            ["Tu ___ ce restaurant ?", "Do you know this restaurant?"],
            ["Elle ___ beaucoup de monde dans cette ville.", "She knows a lot of people in this city."],
            ["Nous ___ les difficultés de ce travail.", "We know the difficulties of this job."],
            ["Vous ___ le nouveau directeur ?", "Do you know the new director?"],
            ["Ils ___ les règles du jeu.", "They know the rules of the game."],
        ],
        subjunctive: [
            ["Il faut que je ___ mieux cette ville.", "I need to get to know this city better."],
            ["Je veux que tu ___ mes amis.", "I want you to get to know my friends."],
            ["Il est important qu'elle ___ les risques.", "It's important that she know the risks."],
            ["Je souhaite que nous ___ la même chose.", "I wish we knew the same things."],
            ["Il faut que vous ___ vos droits.", "You need to know your rights."],
            ["Je veux qu'ils ___ les conséquences.", "I want them to know the consequences."],
        ],
        imperative: [
            ["___ tes limites pour mieux les dépasser.", "Know your limits in order to better surpass them."],
            ["___ mieux nos concurrents pour nous améliorer.", "Let's get to know our competitors better to improve."],
            ["___ vos droits avant de signer.", "Know your rights before signing."],
        ],
        gerund: ["En ___ bien sa langue, on la parle mieux.", "By knowing one's language well, one speaks it better."],
        infinitive: ["Il est utile de ___ plusieurs langues.", "It is useful to know several languages."],
        past_participle: ["Il a ___ le succès très tôt dans sa carrière.", "He experienced success very early in his career."],
    },
    ouvrir: {
        indicative: [
            ["J'___ la fenêtre pour aérer la pièce.", "I open the window to air the room."],
            ["Tu ___ le magasin à quelle heure ?", "What time do you open the shop?"],
            ["Elle ___ la porte à ses invités.", "She opens the door to her guests."],
            ["Nous ___ un nouveau bureau en janvier.", "We are opening a new office in January."],
            ["Vous ___ les colis dès leur arrivée ?", "Do you open the parcels as soon as they arrive?"],
            ["Ils ___ le débat sur ce sujet.", "They are opening the debate on this subject."],
        ],
        subjunctive: [
            ["Il faut que j'___ ce dossier.", "I need to open this file."],
            ["Je veux que tu ___ la fenêtre.", "I want you to open the window."],
            ["Il est important qu'elle ___ son cœur.", "It's important that she open her heart."],
            ["Je souhaite que nous ___ un dialogue.", "I wish we opened a dialogue."],
            ["Il faut que vous ___ les inscriptions.", "You need to open registrations."],
            ["Je veux qu'ils ___ leurs esprits.", "I want them to open their minds."],
        ],
        imperative: [
            ["___ la fenêtre, il fait trop chaud.", "Open the window, it's too hot."],
            ["___ nos esprits à de nouvelles idées.", "Let's open our minds to new ideas."],
            ["___ vos cahiers à la page vingt.", "Open your notebooks to page twenty."],
        ],
        gerund: ["En ___ la discussion, on trouve souvent une solution.", "By opening the discussion, one often finds a solution."],
        infinitive: ["Il faut ___ la porte au changement.", "One must open the door to change."],
        past_participle: ["Le nouveau magasin a ___ ses portes ce matin.", "The new shop opened its doors this morning."],
    },
    jouer: {
        indicative: [
            ["Je ___ au tennis chaque week-end.", "I play tennis every weekend."],
            ["Tu ___ d'un instrument de musique ?", "Do you play a musical instrument?"],
            ["Il ___ du piano depuis l'âge de six ans.", "He has played the piano since the age of six."],
            ["Nous ___ aux échecs le soir.", "We play chess in the evenings."],
            ["Vous ___ dans quel club de football ?", "Which football club do you play for?"],
            ["Ils ___ un match de rugby samedi.", "They are playing a rugby match on Saturday."],
        ],
        subjunctive: [
            ["Il faut que je ___ mieux.", "I need to play better."],
            ["Je veux que tu ___ plus souvent dehors.", "I want you to play outside more often."],
            ["Il est important qu'elle ___ en équipe.", "It's important that she play as a team."],
            ["Je souhaite que nous ___ ensemble.", "I wish we played together."],
            ["Il faut que vous ___ de façon équitable.", "You need to play fairly."],
            ["Je veux qu'ils ___ avec passion.", "I want them to play with passion."],
        ],
        imperative: [
            ["___ dehors avec tes amis.", "Play outside with your friends."],
            ["___ ensemble ce week-end.", "Let's play together this weekend."],
            ["___ votre meilleur jeu ce soir.", "Play your best game tonight."],
        ],
        gerund: ["En ___ régulièrement, il est devenu professionnel.", "By playing regularly, he became a professional."],
        infinitive: ["Il adore ___ de la guitare le soir.", "He loves to play guitar in the evenings."],
        past_participle: ["Ils ont ___ un excellent match.", "They played an excellent match."],
    },
    suivre: {
        indicative: [
            ["Je ___ un cours de français en ligne.", "I am following a French course online."],
            ["Tu ___ l'actualité régulièrement ?", "Do you follow the news regularly?"],
            ["Il ___ ses collègues dans ce nouveau projet.", "He is following his colleagues in this new project."],
            ["Nous ___ vos conseils avec attention.", "We follow your advice carefully."],
            ["Vous ___ encore ce feuilleton ?", "Are you still following this series?"],
            ["Ils ___ un régime strict.", "They are following a strict diet."],
        ],
        subjunctive: [
            ["Il faut que je ___ ce cours jusqu'à la fin.", "I need to follow this course to the end."],
            ["Je veux que tu ___ mes conseils.", "I want you to follow my advice."],
            ["Il est important qu'elle ___ le traitement.", "It's important that she follow the treatment."],
            ["Je souhaite que nous ___ le même chemin.", "I wish we followed the same path."],
            ["Il faut que vous ___ les instructions.", "You need to follow the instructions."],
            ["Je veux qu'ils ___ les règles.", "I want them to follow the rules."],
        ],
        imperative: [
            ["___ les instructions attentivement.", "Follow the instructions carefully."],
            ["___ la même direction pour éviter de nous perdre.", "Let's follow the same direction to avoid getting lost."],
            ["___ ce plan à la lettre.", "Follow this plan to the letter."],
        ],
        gerund: ["En ___ son instinct, elle a pris la bonne décision.", "By following her instinct, she made the right decision."],
        infinitive: ["Il est difficile de ___ un régime strict.", "It is difficult to follow a strict diet."],
        past_participle: ["J'ai ___ ce cours pendant six mois.", "I followed this course for six months."],
    },
    dormir: {
        indicative: [
            ["Je ___ huit heures par nuit.", "I sleep eight hours a night."],
            ["Tu ___ bien en ce moment ?", "Are you sleeping well at the moment?"],
            ["Il ___ encore à dix heures du matin.", "He is still sleeping at ten in the morning."],
            ["Nous ___ souvent tard le week-end.", "We often sleep late at the weekend."],
            ["Vous ___ suffisamment ?", "Do you sleep enough?"],
            ["Ils ___ profondément après une longue journée.", "They sleep deeply after a long day."],
        ],
        subjunctive: [
            ["Il faut que je ___ plus pour récupérer.", "I need to sleep more to recover."],
            ["Je veux que tu ___ suffisamment.", "I want you to sleep enough."],
            ["Il est important qu'il ___ bien avant l'examen.", "It's important that he sleep well before the exam."],
            ["Je souhaite que nous ___ mieux cette nuit.", "I wish we slept better tonight."],
            ["Il faut que vous ___ davantage.", "You need to sleep more."],
            ["Je veux qu'ils ___ bien.", "I want them to sleep well."],
        ],
        imperative: [
            ["___ bien et repose-toi.", "Sleep well and rest."],
            ["___ tôt ce soir pour être en forme demain.", "Let's sleep early tonight to be in good shape tomorrow."],
            ["___ au moins sept heures par nuit.", "Sleep at least seven hours a night."],
        ],
        gerund: ["En ___ suffisamment, on est plus productif.", "By sleeping enough, one is more productive."],
        infinitive: ["Il est essentiel de ___ suffisamment pour rester en bonne santé.", "It is essential to sleep enough to stay healthy."],
        past_participle: ["Avez-vous bien ___ la nuit dernière ?", "Did you sleep well last night?"],
    },
    sentir: {
        indicative: [
            ["Je ___ le parfum des fleurs.", "I smell the fragrance of the flowers."],
            ["Tu ___ cette odeur de pain frais ?", "Do you smell that fresh bread?"],
            ["Elle ___ qu'il se passe quelque chose.", "She feels something is happening."],
            ["Nous ___ la fatigue après cette longue journée.", "We feel the tiredness after this long day."],
            ["Vous ___ le froid ce matin ?", "Do you feel the cold this morning?"],
            ["Ils ___ la pression avant l'examen.", "They feel the pressure before the exam."],
        ],
        subjunctive: [
            ["Il faut que je ___ mieux dans mon travail.", "I need to feel better about my work."],
            ["Je veux que tu ___ à l'aise ici.", "I want you to feel comfortable here."],
            ["Il est important qu'elle ___ soutenue.", "It's important that she feel supported."],
            ["Je souhaite que nous ___ plus proches.", "I wish we felt closer."],
            ["Il faut que vous ___ la différence.", "You need to feel the difference."],
            ["Je veux qu'ils ___ les bienfaits de l'exercice.", "I want them to feel the benefits of exercise."],
        ],
        imperative: [
            ["___ le bon air de la campagne.", "Feel the fresh country air."],
            ["___ la différence que nos actions font.", "Let's feel the difference our actions make."],
            ["___ libres de poser des questions.", "Feel free to ask questions."],
        ],
        gerund: ["En ___ la nature autour de soi, on se détend.", "By feeling nature around oneself, one relaxes."],
        infinitive: ["Il est agréable de ___ le soleil sur sa peau.", "It is pleasant to feel the sun on one's skin."],
        past_participle: ["Il a ___ une grande émotion à ce moment.", "He felt a great emotion at that moment."],
    },
    trouver: {
        indicative: [
            ["Je ___ ce film très intéressant.", "I find this film very interesting."],
            ["Tu ___ ton chemin facilement ?", "Do you find your way easily?"],
            ["Il ___ toujours le bon mot.", "He always finds the right word."],
            ["Nous ___ une solution à ce problème.", "We are finding a solution to this problem."],
            ["Vous ___ ce travail difficile ?", "Do you find this work difficult?"],
            ["Ils ___ leur bonheur dans les petites choses.", "They find their happiness in small things."],
        ],
        subjunctive: [
            ["Il faut que je ___ une solution rapidement.", "I need to find a solution quickly."],
            ["Je veux que tu ___ ce qui te convient.", "I want you to find what suits you."],
            ["Il est important qu'elle ___ un emploi.", "It's important that she find a job."],
            ["Je souhaite que nous ___ un terrain d'entente.", "I wish we found common ground."],
            ["Il faut que vous ___ vos clés.", "You need to find your keys."],
            ["Je veux qu'ils ___ leur voie.", "I want them to find their path."],
        ],
        imperative: [
            ["___ le chemin qui te correspond.", "Find the path that is right for you."],
            ["___ une solution créative à ce problème.", "Let's find a creative solution to this problem."],
            ["___ vos documents avant la réunion.", "Find your documents before the meeting."],
        ],
        gerund: ["En ___ le bon équilibre, on est plus heureux.", "By finding the right balance, one is happier."],
        infinitive: ["Il est difficile de ___ le bon mot parfois.", "It is sometimes difficult to find the right word."],
        past_participle: ["Elle a ___ un emploi dans une grande entreprise.", "She found a job in a large company."],
    },
    changer: {
        indicative: [
            ["Je ___ souvent d'avis sur cette question.", "I often change my mind on this question."],
            ["Tu ___ de travail bientôt ?", "Are you changing jobs soon?"],
            ["Il ___ d'attitude depuis quelques semaines.", "He has been changing his attitude for a few weeks."],
            ["Nous ___ de stratégie pour améliorer les résultats.", "We are changing strategy to improve results."],
            ["Vous ___ souvent de voiture ?", "Do you change your car often?"],
            ["Ils ___ de quartier l'année prochaine.", "They are moving to a different neighbourhood next year."],
        ],
        subjunctive: [
            ["Il faut que je ___ mes habitudes.", "I need to change my habits."],
            ["Je veux que tu ___ d'attitude.", "I want you to change your attitude."],
            ["Il est important qu'elle ___ de méthode.", "It's important that she change her method."],
            ["Je souhaite que nous ___ pour le mieux.", "I wish we changed for the better."],
            ["Il faut que vous ___ votre façon de travailler.", "You need to change your way of working."],
            ["Je veux qu'ils ___ leurs mauvaises habitudes.", "I want them to change their bad habits."],
        ],
        imperative: [
            ["___ d'attitude si tu veux progresser.", "Change your attitude if you want to progress."],
            ["___ de cap et trouvons une nouvelle direction.", "Let's change course and find a new direction."],
            ["___ vos mots de passe régulièrement.", "Change your passwords regularly."],
        ],
        gerund: ["En ___ ses habitudes, on améliore sa vie.", "By changing one's habits, one improves one's life."],
        infinitive: ["Il faut du courage pour ___ de vie.", "It takes courage to change one's life."],
        past_participle: ["Elle a ___ de coiffure pour une nouvelle image.", "She changed her hairstyle for a new look."],
    },
    améliorer: {
        indicative: [
            ["J'___ mon français chaque jour.", "I improve my French every day."],
            ["Tu ___ vraiment ta technique.", "You are really improving your technique."],
            ["Il ___ ses résultats depuis le début de l'année.", "He is improving his results since the start of the year."],
            ["Nous ___ nos processus en continu.", "We continuously improve our processes."],
            ["Vous ___ vos conditions de travail ?", "Are you improving your working conditions?"],
            ["Ils ___ leur performance chaque semaine.", "They improve their performance every week."],
        ],
        subjunctive: [
            ["Il faut que j'___ mon niveau.", "I need to improve my level."],
            ["Je veux que tu ___ ta prononciation.", "I want you to improve your pronunciation."],
            ["Il est important qu'elle ___ ses compétences.", "It's important that she improve her skills."],
            ["Je souhaite que nous ___ notre collaboration.", "I wish we improved our collaboration."],
            ["Il faut que vous ___ vos résultats.", "You need to improve your results."],
            ["Je veux qu'ils ___ leur service client.", "I want them to improve their customer service."],
        ],
        imperative: [
            ["___ ta technique et les résultats viendront.", "Improve your technique and results will come."],
            ["___ notre système pour le rendre plus efficace.", "Let's improve our system to make it more efficient."],
            ["___ vos compétences grâce à des formations.", "Improve your skills through training."],
        ],
        gerund: ["En ___ constamment, on atteint l'excellence.", "By constantly improving, one reaches excellence."],
        infinitive: ["Il est toujours possible d'___ ses compétences.", "It is always possible to improve one's skills."],
        past_participle: ["Elle a considérablement ___ son niveau de français.", "She considerably improved her level of French."],
    },
    rentrer: {
        indicative: [
            ["Je ___ chez moi après le travail.", "I go home after work."],
            ["Tu ___ à quelle heure ce soir ?", "What time are you going home tonight?"],
            ["Il ___ de vacances lundi.", "He is returning from holiday on Monday."],
            ["Nous ___ toujours avant minuit.", "We always return home before midnight."],
            ["Vous ___ directement après la réunion ?", "Are you going straight home after the meeting?"],
            ["Ils ___ de voyage épuisés mais heureux.", "They return from their trip exhausted but happy."],
        ],
        subjunctive: [
            ["Il faut que je ___ avant la nuit.", "I need to get home before nightfall."],
            ["Je veux que tu ___ tôt ce soir.", "I want you to come home early tonight."],
            ["Il est important qu'elle ___ avant dix heures.", "It's important that she come home before ten."],
            ["Je souhaite que nous ___ ensemble.", "I wish we went home together."],
            ["Il faut que vous ___ avant la réunion.", "You need to get back before the meeting."],
            ["Je veux qu'ils ___ sains et saufs.", "I want them to return home safe and sound."],
        ],
        imperative: [
            ["___ avant la nuit, il fait froid.", "Get home before dark, it's cold."],
            ["___ ensemble à pied.", "Let's walk home together."],
            ["___ directement après le cours.", "Go straight home after class."],
        ],
        gerund: ["En ___ à pied, elle décompresse après le travail.", "By walking home, she unwinds after work."],
        infinitive: ["Il est temps de ___ à la maison.", "It is time to go home."],
        past_participle: ["Ils sont ___ fatigués mais satisfaits.", "They returned home tired but satisfied."],
    },
};
